import { Press_Start_2P } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";

// our gaming font
const press = Press_Start_2P({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-press-start'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={press.variable}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
