import { Press_Start_2P } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";

// our gaming font
const press = Press_Start_2P({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-press-start'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={press.variable}>
        <Header />
          <PageTransition>
            {children}
          </PageTransition>
      </body>
    </html>
  );
}
